objects=\
math_amoeba.o\
math_amotry.o\
math_brent.o\
math_cross_product_matrix.o\
math_dmatrix.o\
math_dvector.o\
math_error_handler.o\
math_f1dim.o\
math_free_dvector.o\
math_linmin.o\
math_lubksb.o\
math_ludcmp.o\
math_lu_decomposition_determinant.o\
math_lu_decomposition_inverse.o\
math_lu_decomposition_solve.o\
math_matrix2x2_determinant.o\
math_matrix3x3_determinant.o\
math_matrix3x3_inverse.o\
math_matrix_matrix_product.o\
math_matrix_remove_row_col.o\
math_matrix_transpose.o\
math_matrix_vector_product.o\
math_mnbrak.o\
math_nrerror.o\
math_powell.o\
math_pythag.o\
math_singular_value_decomposition.o\
math_singular_value_decomposition_solve.o\
math_svbksb.o\
math_svdcmp.o\
math_vector_vector_product.o
