objects=\
bicubic_interpolation_on_image.o\
bicubic_interpolation_on_image_int.o\
bilinear_interpolation_on_image_int.o\
cubic_interpolation.o\
error_handler.o\
F.o\
get_random_dbl.o\
get_random_int.o\
linear_interpolation.o\
plot_convex_polygon.o\
plot_line.o\
plot_line_high.o\
plot_line_low.o\
resize_rgb_image.o\
rgb2xyz.o\
rgb_image_to_Lab.o\
xyz2Lab.o
